import { loader } from "fumadocs-core/source";
import { docs } from "@/.source/server";

// The content source: defineDocs + loader, baseUrl /docs. The docs object is
// generated by fumadocs-mdx from source.config.ts and imported via
// @/.source/server (the generated entry point for server-side usage).

export const source = loader({
    source: docs.toFumadocsSource(),
    baseUrl: "/docs",
});
